### ISSUE TITLE
 ImportError: cannot import name 'country_codes' from 'protonvpn_cli'

### ISSUE THREAD

**Issue by cray12399** [jcemerson/protonvpn-cli-gui#16]
Hi, I recently installed your ProtonVPN GUI application on a fully upgraded Ubuntu 20.04 install with kernel version 5.5.4. I am trying to start the application using the command:

`protonvpn-cli-gui`

And when I run it, everything seems to be working fine and the GUI very briefly shows up, but then it immediately crashes and gives me an import error when it tries to import country_codes from protonvpn_cli. I verified that protonvpn_cli is installed on my system and fully updated. This is the terminal output I get when I try to run the application:

```
[WARNING] [Config      ] Older configuration version detected (0 instead of 21)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_20-12-31_0.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.8/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 21.0.0-devel (git-28a202f 2020-12-31 focal-oibaf-ppa)'>
[INFO   ] [GL          ] OpenGL vendor <b'AMD'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.5.4-050504-generic, LLVM 11.0.0)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "/usr/local/bin/protonvpn-cli-gui", line 5, in <module>
     from protonvpn_cli_gui.protonvpnguiapp import pvpn_gui
   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli_gui/protonvpnguiapp.py", line 69, in <module>
     from protonvpn_cli import country_codes as pvpncli_country_codes  # noqa
 ImportError: cannot import name 'country_codes' from 'protonvpn_cli' (/usr/lib/python3/dist-packages/protonvpn_cli/__init__.py)
```

Do you have any idea on how I can fix this issue?
`

**Comment by jcemerson** [comment]
Are you using sudo in your command?

The correct command is:

`sudo protonvpn-cli-gui`

**Comment by jcemerson** [comment]
I'm going to close this issue due to lack of response. If the issue persists, let me know and I can work with you to resolve it.

FYI - ProtonVPN has released a new (beta) Linux CLI with which this GUI is incompatible. I've also learned from the CTO that they've selected another project to become their official GUI (work in progress), so as much as I appreciate you're using my program, between the fact that I'm too busy right now and that an official GUI will be released in the near future, you may be better off going down that path instead. Thanks again for using my program!
